### PR TITLE
AMB-02 Create delivery employee migration

### PR DESCRIPTION
**Pull request by james-liam-butler**

### CODE REVIEW

**Review by dana-kainos — CHANGES_REQUESTED** [review]
change name of PR to AMB-02 and capitalize C

**Review by CharlotteMKainos — CHANGES_REQUESTED** [review]
capitalise all SQL commands

**Review by CharlotteMKainos — CHANGES_REQUESTED** [review]
remove currency data field

**Review by james-liam-butler — COMMENTED** [review]
Rename changes

**Review by CharlotteMKainos — APPROVED** [review]

**Review by lukemKainos — APPROVED** [review]

**Review by dana-kainos — APPROVED** [review]

**Pull request merged**
